name: Generate Custom Contribution Chart

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

# این بخش دسترسی نوشتن را به صورت قطعی برای این اکشن باز می‌کند
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          npm init -y
          npm pkg set type="module"
          node generate-chart.js

      - name: Commit and Push SVG
        run: |
          git config --global user.name "wasteodd"
          git config --global user.email "wasteodd@users.noreply.github.com"
          git add contributions.svg
          git commit -m "auto: update custom contributions chart" || echo "No changes to commit"
          git push
